data_root: data

data_ingestion:
  root_dir: data/data_ingestion
  data_path: data/MentalHealthSurvey.csv

data_loading:
  root_dir: data/data_loading
  data_path: data/data_ingestion/MentalHealthSurvey.csv
  X_train: data/data_loading/X_train.csv
  X_test: data/data_loading/X_test.csv
  y_train: data/data_loading/y_train.csv
  y_test: data/data_loading/y_test.csv

data_preprocessing:
  root_dir: data/data_preprocessing
  X_train: data/data_loading/X_train.csv
  X_test: data/data_loading/X_test.csv
  y_train: data/data_loading/y_train.csv
  y_test: data/data_loading/y_test.csv
  X_train_processed: data/data_preprocessing/X_train_processed.csv
  X_test_processed: data/data_preprocessing/X_test_processed.csv
  y_train_processed: data/data_preprocessing/y_train_processed.csv
  y_test_processed: data/data_preprocessing/y_test_processed.csv 

model_training:
  root_dir: data/model_training
  model_path: data/model_training/rfc.pkl
  X_train_processed: data/data_preprocessing/X_train_processed.csv
  y_train_processed: data/data_loading/y_train.csv